### ISSUE TITLE
Confusion on the configuration in Training

### ISSUE THREAD

**Issue by tsunghan-wu** [Abhiram4572/mi_bart#2]
Hi authors,

Thanks for the great work! I was wondering that do you always feed two images to the MI-BART backbone in the implementation? Thanks!

**Comment by Abhiram4572** [comment]
Hi, thanks for exploring our work. 

Earlier we had a generic version where we use an additional parameter k (<=4) to let the model know the number of images so that it could differentiate features of different images. In this case, for those samples which have less than 4 images, we pad zeros in their place. 

However, after conducting few experiments, owing to our dataset restrictions, K=2 yielded better results.
For RETVQA, we always have multiple-images (i.e., 2), for WebQA training we do not have multiple images for all samples, in such cases we pad with zeros (in place of extra image features).
